name: Variables and Secrets

on:
  workflow_dispatch:

env:
    MY_SECRET: ${{ secrets.GPRSECRET }}
    MY_ENV_VAR: ${{ vars.GPRVAR }}

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: echo docker build -t ${{ env.MY_ENV_VAR }} - ${{ env.MY_SECRET }}

            - name: Docker login
              run: echo docker login -u ${{ secrets.GPRUSER }} -p ${{ secrets.GPRSECRET }}

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              run: |
                   echo Deploying ${{ env.MY_ENV_VAR }} with ${{ env.MY_SECRET }}
                   sleep 600s


